name: Cypress tests

on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          build: yarn build
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          EMAIL_ERROR: ${{ secrets.EMAIL_ERROR }}
          PASSWD_ERROR: ${{ secrets.PASSWD_ERROR }}
